import "./globals.css";
import { Poppins } from "next/font/google";
import { DeviceProvider } from "@/utils/deviceContext";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <DeviceProvider>{children}</DeviceProvider>
      </body>
    </html>
  );
}
